name: Build Release

permissions:
  attestations: write
  contents: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Release
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          cache: true
          channel: stable
          flutter-version-file: .fvmrc

      - name: Fetch dependencies
        run: |
          set -eu
          flutter config --no-analytics
          flutter pub get

      - name: Prepare signing
        env:
          KEY_ALIAS: piwigong
          STORE_PASSWORD: '${{ secrets.STORE_PASSWORD }}'
          STORE_FILE: '${{ runner.temp }}/signing-keystore.jks'
        shell: bash
        run: |
          set -eu
          echo "keyAlias=${KEY_ALIAS}" > "android/key.properties"
          echo "keyPassword=${STORE_PASSWORD}" >> "android/key.properties"
          echo "storePassword=${STORE_PASSWORD}" >> "android/key.properties"
          echo "storeFile=${STORE_FILE}" >> "android/key.properties"

      - name: Build app
        env:
          STORE_FILE: '${{ runner.temp }}/signing-keystore.jks'
        run: |
          set -eu
          trap 'rm -f "${STORE_FILE}" android/key.properties' EXIT
          echo '${{ secrets.STORE_BASE64 }}' | base64 -d > "${STORE_FILE}"
          flutter build apk --release --split-per-abi

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: piwigong-app-arm64-v8a
          path: build/app/outputs/flutter-apk/app-*-release.apk

      - name: Create GitHub build provenance attestations
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: build/app/outputs/flutter-apk/app-*-release.apk

      - name: Determine release tag
        id: version
        run: |
          set -eu
          VERSION=$(sed -n 's/^version: *\([^+]*\).*/\1/p' pubspec.yaml)
          echo "tag=v${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Create draft release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          tag: ${{ steps.version.outputs.tag }}
          artifacts: "build/app/outputs/flutter-apk/app-*-release.apk"
          artifactErrorsFailBuild: true
          name: PiwigoNG ${{ steps.version.outputs.tag }}
          prerelease: false
          draft: true
